import React,{useEffect,useMemo,useState}from'react';
import ReactDOM from'react-dom/client';
import'./index.css';
import{today,normState,save,fp,find,parseDT,num,uid,stats}from'./core.js';
import{Dashboard,Journal,Importer,Analytics}from'./pages1.jsx';
import{Review,Risk,Backup,Settings,Edit}from'./pages2.jsx';
import{Readiness,Playbook,ScreenshotReview,Excursion,BracketLab,Coach}from'./pages3.jsx';
function App(){const[data,setData]=useState(normState),[tab,setTab]=useState('coach'),[mode,setMode]=useState('SIM'),[msg,setMsg]=useState(''),[editing,setEditing]=useState(null),[filters,setFilters]=useState({preset:'all',from:'',to:'',instrument:'',direction:'',setup:'',minScore:'',search:''});useEffect(()=>{document.documentElement.dataset.theme=data.settings.theme||'dark';save(data)},[data]);useEffect(()=>{if(!msg)return;const x=setTimeout(()=>setMsg(''),4500);return()=>clearTimeout(x)},[msg]);const raw=useMemo(()=>data.trades.filter(t=>t.accountType===mode),[data.trades,mode]);const filtered=useMemo(()=>{const now=new Date(),cut=new Date(now);if(filters.preset==='today')cut.setHours(0,0,0,0);if(filters.preset==='week')cut.setDate(now.getDate()-6);if(filters.preset==='month')cut.setDate(1);return raw.filter(t=>{const d=new Date(`${t.date}T00:00:00`);return(!['today','week','month'].includes(filters.preset)||d>=cut)&&(!filters.from||t.date>=filters.from)&&(!filters.to||t.date<=filters.to)&&(!filters.instrument||t.instrument===filters.instrument)&&(!filters.direction||t.direction===filters.direction)&&(!filters.setup||t.setup===filters.setup)&&(!filters.minScore||t.score>=+filters.minScore)&&(!filters.search||JSON.stringify(t).toLowerCase().includes(filters.search.toLowerCase()))})},[raw,filters]);const s=useMemo(()=>stats(filtered),[filtered]);
const importRows=(rows,type)=>{const old=new Set(data.trades.map(fp)),seen=new Set(),arr=[];rows.forEach(r=>{const dt=parseDT(find(r,['close date','entry time','exit time','date']),find(r,['time'])),side=find(r,['direction','side','action']),gross=num(find(r,['gross pnl','gross p&l','gross profit','pnl','p&l','profit'])),commission=Math.abs(num(find(r,['commission','fees','fee']))),netRaw=find(r,['net pnl','net p&l','net profit']);const t={id:uid(),accountType:type,date:dt.date,time:dt.time,instrument:find(r,['instrument','symbol'])||data.settings.defaultInstrument,direction:/sell|short/i.test(side)?'Short':'Long',contracts:num(find(r,['quantity','qty','contracts']))||1,entry:num(find(r,['entry'])),exit:num(find(r,['exit'])),gross,commission,pnl:netRaw!==''?num(netRaw):gross-commission,setup:'Imported',emotion:'Not recorded',mistake:'None',notes:'Imported from NinjaTrader CSV',score:0,rules:Array(10).fill(false),screenshot:'',beforeScreenshot:'',afterScreenshot:'',mfe:0,mae:0,bracket:'Unassigned',stopTicks:0,targetTicks:0};const f=fp(t);if(!old.has(f)&&!seen.has(f)){seen.add(f);arr.push(t)}});if(!arr.length){setMsg('No new trades found. Duplicate rows were skipped.');return}setData(d=>({...d,trades:[...d.trades,...arr]}));setMode(type);setTab('dashboard');setMsg(`${arr.length} ${type} trades imported. ${rows.length-arr.length} duplicates skipped.`)};
const tabs=['coach','dashboard','journal','import','analytics','readiness','playbook','screenshots','excursion','brackets','review','risk','backup','settings'];
return <div className="app"><aside><h2>MES Command Center</h2><small>SIM and LIVE journals</small><div className="mode"><button className={mode==='SIM'?'on':''} onClick={()=>setMode('SIM')}>SIM</button><button className={mode==='LIVE'?'on live':''} onClick={()=>setMode('LIVE')}>LIVE</button></div>{tabs.map(x=><button className={tab===x?'nav on':'nav'} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</aside><main>{msg&&<div className="toast">{msg}</div>}{tab==='coach'&&<Coach trades={raw} settings={data.settings[mode]}/>} {tab==='dashboard'&&<Dashboard mode={mode} trades={filtered} stats={s} filters={filters} setFilters={setFilters} settings={data.settings[mode]} edit={setEditing} del={id=>setData(d=>({...d,trades:d.trades.filter(t=>t.id!==id)}))}/>} {tab==='journal'&&<Journal mode={mode} settings={data.settings} onSave={t=>{setData(d=>({...d,trades:[...d.trades,{...t,beforeScreenshot:t.screenshot||'',afterScreenshot:'',mfe:0,mae:0,bracket:'Unassigned',stopTicks:0,targetTicks:0}]}));setMode(t.accountType);setTab('dashboard');setMsg('Trade saved.')}}/>}{tab==='import'&&<Importer onRows={importRows}/>} {tab==='analytics'&&<Analytics trades={filtered}/>} {tab==='readiness'&&<Readiness trades={data.trades}/>} {tab==='playbook'&&<Playbook/>} {tab==='screenshots'&&<ScreenshotReview trades={raw}/>} {tab==='excursion'&&<Excursion trades={raw}/>} {tab==='brackets'&&<BracketLab trades={raw} onSave={b=>{setData(d=>({...d,brackets:[...(d.brackets||[]),b]}));setMsg('Bracket template saved.')}}/>} {tab==='review'&&<Review mode={mode} trades={raw} reviews={data.reviews} goals={data.goals} onSave={(k,v)=>setData(d=>({...d,reviews:{...d.reviews,[k]:v}}))} onGoal={(k,v)=>setData(d=>({...d,goals:{...d.goals,[k]:v}}))}/>} {tab==='risk'&&<Risk mode={mode} settings={data.settings[mode]} trades={raw}/>} {tab==='backup'&&<Backup data={data} setData={setData} trades={filtered}/>} {tab==='settings'&&<Settings data={data} setData={setData}/>} {editing&&<Edit trade={editing} onClose={()=>setEditing(null)} onSave={t=>{setData(d=>({...d,trades:d.trades.map(x=>x.id===t.id?t:x)}));setEditing(null);setMsg('Trade updated.')}}/>}</main></div>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);