export const KEY='mes-command-center-v5',today=()=>new Date().toISOString().slice(0,10),money=n=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'}),uid=()=>crypto.randomUUID();
export const defaults={trades:[],reviews:{},goals:{},settings:{theme:'dark',defaultInstrument:'MES',SIM:{startingBalance:50000,maxDailyLoss:60,maxTrades:5,minRuleScore:80,maxRisk:20},LIVE:{startingBalance:150,maxDailyLoss:60,maxTrades:5,minRuleScore:80,maxRisk:20},windowStart:'09:30',windowEnd:'11:00'}};
export const rules=['Inside approved trading window','Aligned with 5M/15M bias','Price aligned with 100 EMA','Entry came from marked zone','1M confirmation present','Stop defined before entry','ATM/bracket confirmed','Risk/reward at least 1:2','No FOMO/revenge trade','Daily loss limit respected'];
export const setups=['Riley EMA Trend','Supply/Demand Zone','Breakout','Reversal','Other'],mistakes=['None','Overtrading','Outside trading window','Early entry','Chasing','No confirmed bracket','Ignored bias','Second contract too early','FOMO','Revenge trade'];
export function normState(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem('mes-command-center-v4')||'{}',s=JSON.parse(raw);const oldSettings=s.settings||{},simOld={startingBalance:oldSettings.startingBalance,maxDailyLoss:oldSettings.maxDailyLoss,maxTrades:oldSettings.maxTrades,minRuleScore:oldSettings.minRuleScore};const out={...defaults,...s,goals:s.goals||{},settings:{...defaults.settings,...oldSettings,SIM:{...defaults.settings.SIM,...simOld,...oldSettings.SIM},LIVE:{...defaults.settings.LIVE,...oldSettings.LIVE}},trades:(s.trades||[]).map(t=>({...t,accountType:t.accountType||'SIM',commission:Number(t.commission||0),gross:Number(t.gross??t.pnl??0),pnl:Number(t.pnl||0),score:Number(t.score||0)}))};localStorage.setItem(KEY,JSON.stringify(out));return out}catch{return structuredClone(defaults)}}
export const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
export const num=v=>{const s=String(v??'').replace(/[$,]/g,'').trim();return /^\(.*\)$/.test(s)?-Number(s.slice(1,-1)):Number(s)||0};
export const find=(r,n)=>{const k=Object.keys(r).find(k=>n.some(x=>k.toLowerCase().includes(x)));return k?r[k]:''};
export const parseDT=(a,b='')=>{const z=`${a||''} ${b||''}`,u=[...z.matchAll(/(\d{1,2})\/(\d{1,2})\/(\d{4})/g)],i=[...z.matchAll(/(\d{4})-(\d{2})-(\d{2})/g)],tm=[...z.matchAll(/(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?/gi)];let d=today(),t='';if(u.length){const m=u.at(-1);d=`${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`}else if(i.length){const m=i.at(-1);d=`${m[1]}-${m[2]}-${m[3]}`}if(tm.length){const m=tm.at(-1);let h=+m[1],p=(m[4]||'').toUpperCase();if(p==='PM'&&h<12)h+=12;if(p==='AM'&&h===12)h=0;t=`${String(h).padStart(2,'0')}:${m[2]}`}return{date:d,time:t}};
export const fp=t=>[t.accountType,t.date,t.time,t.instrument,t.direction,t.entry,t.exit,t.pnl].join('|');
export function stats(a){const w=a.filter(x=>x.pnl>0),l=a.filter(x=>x.pnl<0),net=a.reduce((s,x)=>s+x.pnl,0),gw=w.reduce((s,x)=>s+x.pnl,0),gl=Math.abs(l.reduce((s,x)=>s+x.pnl,0));let e=0,p=0,dd=0;[...a].sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time)).forEach(x=>{e+=x.pnl;p=Math.max(p,e);dd=Math.max(dd,p-e)});return{net,count:a.length,win:a.length?w.length/a.length*100:0,pf:gl?gw/gl:gw?99:0,avgW:w.length?gw/w.length:0,avgL:l.length?gl/l.length:0,dd,score:a.length?a.reduce((s,x)=>s+x.score,0)/a.length:0}}
export function group(a,key){const m={};a.forEach(x=>{const k=key(x)||'Unknown';(m[k]??={count:0,pnl:0,wins:0});m[k].count++;m[k].pnl+=x.pnl;if(x.pnl>0)m[k].wins++});return Object.entries(m).map(([name,v])=>({name,...v,win:v.count?v.wins/v.count*100:0})).sort((a,b)=>b.pnl-a.pnl)}