import React,{useMemo,useState}from'react';
import{money}from'./core.js';

export function GuidedHome({mode,trades,onGo}){
 const modeTrades=trades.filter(t=>(t.accountType||'SIM')===mode),needs=modeTrades.filter(t=>(t.tradeGrade||'Unrated')==='Unrated'||!t.checklistPct),today=new Date().toISOString().slice(0,10),todayTrades=modeTrades.filter(t=>t.date===today);
 const steps=[
  {phase:'BEFORE TRADING',title:'Prepare the market',text:'Review the 15-minute bias, mark major zones, confirm SIM or LIVE, and set your daily risk.',action:'Open Chart Markup',tab:'charts'},
  {phase:'DURING TRADING',title:'Wait for a valid Riley setup',text:'Use one MES contract, wait for confirmation, verify risk below $25, and require at least 2:1 reward-to-risk.',action:'Journal a Trade',tab:'entry'},
  {phase:'AFTER TRADING',title:'Record the actual execution',text:'Import your NinjaTrader CSV, then connect the financial result to your Riley process review.',action:'Import NinjaTrader CSV',tab:'import'},
  {phase:'END OF DAY',title:'Review discipline, not just profit',text:'Complete every imported trade review and study your process score before judging the day.',action:'Review Imported Trades',tab:'reviewQueue'},
  {phase:'END OF WEEK',title:'Find what is improving',text:'Study patterns, emotions, timing, grades, and confirmation quality.',action:'Find My Strengths',tab:'analytics'}
 ];
 return <><header><div><p>START HERE</p><h1>Today’s Riley Workflow</h1></div><div className="modeBadge">{mode} MODE</div></header><section className="homeSummary"><div><span>Trades today</span><b>{todayTrades.length}</b></div><div><span>Needs Riley review</span><b>{needs.length}</b></div><div><span>Selected account</span><b>{mode}</b></div></section><div className="workflowGrid">{steps.map((s,i)=><section className="workflowCard"><div className="stepNumber">{i+1}</div><p>{s.phase}</p><h2>{s.title}</h2><span>{s.text}</span><button className="primary" onClick={()=>onGo(s.tab)}>{s.action}</button></section>)}</div>{!modeTrades.length&&<section className="emptyGuide"><h2>No {mode} trades yet</h2><p>Start by importing your NinjaTrader Trade Performance CSV or journal a trade manually.</p><div><button className="primary" onClick={()=>onGo('import')}>Import NinjaTrader CSV</button><button onClick={()=>onGo('entry')}>Journal a Trade</button></div></section>}{needs.length>0&&<section className="attentionCard"><div><p>REQUIRES ATTENTION</p><h2>{needs.length} imported trades still need Riley review</h2><span>Imported trades show P&amp;L immediately, but process scores remain incomplete until you add the pattern, zone, checklist, emotion, and review.</span></div><button className="primary" onClick={()=>onGo('reviewQueue')}>Review Now</button></section>}</>}

export function Onboarding({onFinish,onGo}){
 const[step,setStep]=useState(0),[mode,setMode]=useState('SIM');
 const pages=[
  <div><p>STEP 1 OF 4</p><h1>Choose your starting mode</h1><p>Use SIM while proving that you can repeat the process. LIVE should only be used after consistent rule compliance.</p><div className="bigChoice"><button className={mode==='SIM'?'active':''} onClick={()=>setMode('SIM')}>SIM</button><button className={mode==='LIVE'?'active live':''} onClick={()=>setMode('LIVE')}>LIVE</button></div></div>,
  <div><p>STEP 2 OF 4</p><h1>Confirm Michael’s risk rules</h1><ul className="tourList"><li>MES only</li><li>One contract only</li><li>$20 preferred risk</li><li>$25 maximum risk</li><li>Minimum 2:1 reward-to-risk</li><li>Five trades maximum</li></ul></div>,
  <div><p>STEP 3 OF 4</p><h1>Bring in your trading history</h1><p>Export a Trade Performance CSV from NinjaTrader. Import it into SIM or LIVE, then review each imported trade for process quality.</p><button className="primary" onClick={()=>{onGo('import');onFinish(mode)}}>Open Import Page</button></div>,
  <div><p>STEP 4 OF 4</p><h1>Use the same workflow every day</h1><ol className="tourList"><li>Mark the chart</li><li>Wait for confirmation</li><li>Journal the trade</li><li>Import NinjaTrader results</li><li>Review process scores</li><li>Study weekly analytics</li></ol></div>
 ];
 return <div className="tourOverlay"><div className="tourCard">{pages[step]}<div className="tourActions"><button onClick={()=>onFinish(mode)}>Skip tutorial</button>{step>0&&<button onClick={()=>setStep(step-1)}>Back</button>}{step<pages.length-1?<button className="primary" onClick={()=>setStep(step+1)}>Next</button>:<button className="primary" onClick={()=>onFinish(mode)}>Start Using the App</button>}</div></div></div>
}

export function HelpPage({onGo}){
 const sections=[
  ['1. Before the market','Select SIM or LIVE, review the 15-minute bias, identify major zones, and mark the chart before considering an entry.','charts','Open Chart Markup'],
  ['2. Before entering','Use Journal a Trade. Confirm one MES contract, a structural stop, less than $25 risk, at least 2:1 reward-to-risk, and entry after confirmation.','entry','Journal a Trade'],
  ['3. After exiting','Complete exit price, required screenshots, emotional state, and post-trade questions. A losing trade can still receive a strong process grade.','entry','Open Trade Journal'],
  ['4. End of day','Import the NinjaTrader CSV. Imported trades provide account results but still require Riley classification and review.','import','Import NinjaTrader CSV'],
  ['5. End of week','Use Find My Strengths to compare patterns, zones, emotions, grades, checklist completion, and confirmation quality.','analytics','Open Analytics']
 ];
 return <><header><div><p>APP GUIDE</p><h1>How to Use Riley Reversal Journal Pro</h1></div></header><section className="dashboardDifference"><div><h2>SIM / LIVE Results</h2><p>Shows what happened financially in the selected NinjaTrader account.</p></div><div><h2>Discipline Scorecard</h2><p>Shows whether you followed Riley’s process, regardless of whether the trade won or lost.</p></div></section>{sections.map(([title,text,tab,button])=><section className="helpStep"><h2>{title}</h2><p>{text}</p><button className="primary" onClick={()=>onGo(tab)}>{button}</button></section>)}</>}

export function ReviewQueue({mode,trades,onUpdate}){
 const rows=useMemo(()=>trades.filter(t=>(t.accountType||'SIM')===mode&&((t.tradeGrade||'Unrated')==='Unrated'||!t.checklistPct)),[trades,mode]),[selected,setSelected]=useState(rows[0]?.id||''),trade=rows.find(t=>t.id===selected)||rows[0],[form,setForm]=useState({});
 React.useEffect(()=>{if(trade)setForm({pattern:trade.pattern==='Imported'?'':trade.pattern||'',zone:trade.zone||'',beforeEmotion:trade.beforeEmotion||'Calm',afterEmotion:trade.afterEmotion||'Calm',waitedForConfirmation:!!trade.waitedForConfirmation,chased:!!trade.chased,followedStop:trade.followedStop!==false,followedTarget:trade.followedTarget!==false,why:trade.why||'',confirmation:trade.confirmation||'',improve:trade.improve||''})},[trade?.id]);
 const complete=form.pattern&&form.zone&&form.why&&form.confirmation&&form.improve;const checklistPct=Math.round(([form.waitedForConfirmation,!form.chased,form.followedStop,form.followedTarget].filter(Boolean).length/4)*100),grade=checklistPct>=95?'A+':checklistPct>=90?'A':checklistPct>=80?'B':checklistPct>=70?'C':'F';
 if(!rows.length)return <><header><div><p>REVIEW QUEUE</p><h1>Imported Trades Needing Review</h1></div></header><section className="emptyGuide"><h2>All {mode} trades are reviewed</h2><p>Your imported trades now include enough process information to support the Riley scorecards.</p></section></>;
 return <><header><div><p>REVIEW QUEUE</p><h1>Imported Trades Needing Review</h1></div><strong>{rows.length} remaining</strong></header><section><label>Select imported trade<select value={trade?.id||''} onChange={e=>setSelected(e.target.value)}>{rows.map(t=><option value={t.id}>{t.date} {t.time} · {t.instrument} · {money(t.pnl)}</option>)}</select></label></section>{trade&&<section><h2>{trade.date} {trade.time} · {trade.direction} · {money(trade.pnl)}</h2><div className="form two"><label>Riley Pattern<input value={form.pattern||''} onChange={e=>setForm({...form,pattern:e.target.value})} placeholder="Example: Bullish Engulfing"/></label><label>Zone<input value={form.zone||''} onChange={e=>setForm({...form,zone:e.target.value})} placeholder="Demand, support, reversal zone..."/></label><label>Why did I take this trade?<textarea value={form.why||''} onChange={e=>setForm({...form,why:e.target.value})}/></label><label>What confirmation occurred?<textarea value={form.confirmation||''} onChange={e=>setForm({...form,confirmation:e.target.value})}/></label><label className="wide">What will I improve next time?<textarea value={form.improve||''} onChange={e=>setForm({...form,improve:e.target.value})}/></label></div><div className="reviewToggles"><label><input type="checkbox" checked={form.waitedForConfirmation} onChange={e=>setForm({...form,waitedForConfirmation:e.target.checked})}/>Waited for confirmation</label><label><input type="checkbox" checked={form.chased} onChange={e=>setForm({...form,chased:e.target.checked})}/>Chased the move</label><label><input type="checkbox" checked={form.followedStop} onChange={e=>setForm({...form,followedStop:e.target.checked})}/>Followed stop</label><label><input type="checkbox" checked={form.followedTarget} onChange={e=>setForm({...form,followedTarget:e.target.checked})}/>Followed target</label></div><div className="reviewPreview"><span>Estimated checklist</span><b>{checklistPct}%</b><span>Estimated grade</span><b>{grade}</b></div><button className="primary" disabled={!complete} onClick={()=>onUpdate({...trade,...form,checklistPct,processScore:checklistPct,disciplineScore:checklistPct,consistencyScore:checklistPct,riskScore:form.followedStop?100:60,patienceScore:form.waitedForConfirmation&&!form.chased?100:50,confirmationPct:form.waitedForConfirmation?100:0,tradeGrade:grade})}>{complete?'Save Riley Review':'Complete all required review fields'}</button></section>}</>}
