import React,{useMemo,useState}from'react';
import Papa from'papaparse';
import{find,money,num,parseDT,stats,uid,fp}from'./core.js';

export function TradeImport({existing,onImport}){
 const[file,setFile]=useState(null),[mode,setMode]=useState('SIM'),[preview,setPreview]=useState([]),[rows,setRows]=useState([]);
 const read=f=>{setFile(f);setPreview([]);setRows([]);if(!f)return;Papa.parse(f,{header:true,skipEmptyLines:true,complete:r=>{setRows(r.data);setPreview(r.data.slice(0,5))}})};
 const build=()=>{const old=new Set(existing.map(fp)),seen=new Set(),mapped=[];rows.forEach(r=>{const dt=parseDT(find(r,['close date','entry time','exit time','date']),find(r,['time']));const side=find(r,['direction','side','action']);const gross=num(find(r,['gross pnl','gross p&l','gross profit','pnl','p&l','profit']));const commission=Math.abs(num(find(r,['commission','fees','fee'])));const netRaw=find(r,['net pnl','net p&l','net profit']);const t={id:uid(),accountType:mode,date:dt.date,time:dt.time,instrument:find(r,['instrument','symbol'])||'MES',direction:/sell|short/i.test(side)?'Short':'Long',contracts:num(find(r,['quantity','qty','contracts']))||1,entry:num(find(r,['entry'])),exit:num(find(r,['exit'])),gross,commission,pnl:netRaw!==''?num(netRaw):gross-commission,pattern:'Imported',tradeGrade:'Unrated',checklistPct:0,processScore:0,disciplineScore:0,consistencyScore:0,riskScore:0,patienceScore:0,confirmationPct:0,notes:'Imported from NinjaTrader CSV'};const key=fp(t);if(!old.has(key)&&!seen.has(key)){seen.add(key);mapped.push(t)}});onImport(mapped,rows.length-mapped.length,mode)};
 return <><header><div><p>NINJATRADER IMPORT</p><h1>Import Trades</h1></div></header><section><div className="importMode"><button className={mode==='SIM'?'active':''} onClick={()=>setMode('SIM')}>Import to SIM</button><button className={mode==='LIVE'?'active live':''} onClick={()=>setMode('LIVE')}>Import to LIVE</button></div><input type="file" accept=".csv,text/csv" onChange={e=>read(e.target.files?.[0])}/>{file&&<p>Selected: {file.name}</p>}<button className="primary" disabled={!rows.length} onClick={build}>Import {rows.length||0} Rows to {mode}</button>{preview.length>0&&<><h3>Preview</h3><div className="tableWrap"><table><thead><tr>{Object.keys(preview[0]).slice(0,8).map(k=><th>{k}</th>)}</tr></thead><tbody>{preview.map(r=><tr>{Object.keys(preview[0]).slice(0,8).map(k=><td>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></>}</section></>}

export function AccountDashboard({mode,trades,onDelete}){
 const rows=useMemo(()=>trades.filter(t=>(t.accountType||'SIM')===mode),[trades,mode]),s=stats(rows),daily={};rows.forEach(t=>daily[t.date]=(daily[t.date]||0)+Number(t.pnl||0));const recent=[...rows].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).slice(0,20);
 return <><header><div><p>{mode} ACCOUNT</p><h1>{mode} Trade Dashboard</h1></div><strong>{rows.length} trades</strong></header><div className="metricgrid">{[['Net P&L',money(s.net)],['Win Rate',s.win.toFixed(1)+'%'],['Profit Factor',s.pf.toFixed(2)],['Average Winner',money(s.avgW)],['Average Loser',money(s.avgL)],['Max Drawdown',money(s.dd)],['Process Score',Math.round(rows.length?rows.reduce((a,t)=>a+Number(t.processScore||0),0)/rows.length:0)],['Checklist %',Math.round(rows.length?rows.reduce((a,t)=>a+Number(t.checklistPct||0),0)/rows.length:0)+'%']].map(([n,v])=><div><span>{n}</span><b>{v}</b></div>)}</div><section><h2>{mode} Trading Calendar</h2><div className="calendarGrid">{Object.entries(daily).sort().map(([d,p])=><div className={p>=0?'dayWin':'dayLoss'}><span>{d}</span><b>{money(p)}</b></div>)}</div></section><section><h2>Recent {mode} Trades</h2><div className="tableWrap"><table><thead><tr><th>Date</th><th>Instrument</th><th>Side</th><th>Pattern</th><th>Grade</th><th>Process</th><th>P&L</th><th></th></tr></thead><tbody>{recent.map(t=><tr><td>{t.date} {t.time}</td><td>{t.instrument}</td><td>{t.direction}</td><td>{t.pattern||'Imported'}</td><td>{t.tradeGrade||'Unrated'}</td><td>{t.processScore||0}</td><td className={t.pnl>=0?'good':'bad'}>{money(t.pnl)}</td><td><button className="danger" onClick={()=>onDelete(t.id)}>Delete</button></td></tr>)}</tbody></table></div></section></>}
