import React,{useMemo,useState}from'react';
import{money,stats,today,uid}from'./core.js';

const playbooks=[
 {name:'EMA Trend Pullback',level:'Primary',conditions:['15M/5M bias aligned','Price on correct side of 100 EMA','Pullback into structure or zone','1M confirmation closes'],entry:'Enter after confirmation closes and risk is defined.',stop:'Beyond the pullback swing with a 2–4 tick buffer.',target:'Minimum 2R or next major level.',avoid:'Avoid chasing extended candles or entering directly into resistance.'},
 {name:'Supply/Demand Rejection',level:'Primary',conditions:['Fresh marked zone','Clear rejection','Higher-timeframe bias supports trade','Room to target'],entry:'Enter after rejection and confirmation.',stop:'Outside the zone and rejection wick.',target:'Opposing zone or 2R.',avoid:'Avoid repeatedly tested zones and weak reactions.'},
 {name:'Breakout and Retest',level:'Secondary',conditions:['Clear range or level','Strong close through level','Controlled retest','Retest holds'],entry:'Enter after the retest confirms.',stop:'Back inside the broken range.',target:'Measured move or next structure.',avoid:'Avoid first-candle chasing and false breaks.'},
 {name:'Reversal',level:'SIM Only',conditions:['Major higher-timeframe level','Exhaustion evidence','Failed continuation','Confirmed structure shift'],entry:'Only after structure changes.',stop:'Beyond reversal extreme.',target:'First opposing structure.',avoid:'Do not countertrend trade without confirmation.'}
];

export function Readiness({trades}){const sim=trades.filter(t=>t.accountType==='SIM').sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).slice(0,30),s=stats(sim),last10=sim.slice(0,10),violations=last10.filter(t=>t.mistake&&t.mistake!=='None').length,weeks=new Set(sim.filter(t=>t.pnl>0).map(t=>{const d=new Date(t.date+'T12:00');const one=new Date(d.getFullYear(),0,1);return `${d.getFullYear()}-${Math.ceil((((d-one)/86400000)+one.getDay()+1)/7)}`})).size,aGrade=sim.filter(t=>t.score>=90).length;const checks=[['20+ SIM trades',sim.length>=20,`${sim.length}/20`],['Rule score 85+',s.score>=85,`${s.score.toFixed(0)}/85`],['Profit factor 1.5+',s.pf>=1.5,s.pf.toFixed(2)],['No major violation in last 10',violations===0,`${violations} violations`],['Two profitable weeks',weeks>=2,`${weeks}/2`],['At least 50% A-grade setups',sim.length&&aGrade/sim.length>=.5,`${sim.length?Math.round(aGrade/sim.length*100):0}%`]],passed=checks.filter(x=>x[1]).length,pct=Math.round(passed/checks.length*100);return <><header><div><p>SIM TO LIVE</p><h1>Live Readiness Tracker</h1></div><strong>{pct}% Ready</strong></header><section><div className="readiness"><div style={{width:pct+'%'}}></div></div>{checks.map(([n,ok,v])=><div className="readyrow"><span>{ok?'✓':'○'} {n}</span><b className={ok?'good':'bad'}>{v}</b></div>)}</section><section><h2>Decision</h2><div className={pct===100?'approval':'warning'}>{pct===100?'All readiness standards are met. Begin LIVE only with one MES contract and the same rules.':'Continue SIM. Do not use isolated winning days as proof of readiness.'}</div></section></>}

export function Playbook(){const[open,setOpen]=useState(playbooks[0].name);return <><header><h1>Trading Playbook</h1></header>{playbooks.map(p=><section className="playbook"><button className="playhead" onClick={()=>setOpen(open===p.name?'':p.name)}><span>{p.name}</span><b>{p.level}</b></button>{open===p.name&&<div className="playbody"><h3>Required conditions</h3><ul>{p.conditions.map(x=><li>{x}</li>)}</ul><div className="playgrid"><div><b>Entry</b><p>{p.entry}</p></div><div><b>Stop</b><p>{p.stop}</p></div><div><b>Target</b><p>{p.target}</p></div><div><b>Do not trade when</b><p>{p.avoid}</p></div></div></div>}</section>)}</>}

const readImage=(file,done)=>{if(!file)return;const r=new FileReader();r.onload=()=>done(r.result);r.readAsDataURL(file)};
export function ScreenshotReview({trades,onUpdate}){const sorted=[...trades].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)),[selected,setSelected]=useState(sorted[0]?.id||'');const trade=sorted.find(t=>t.id===selected);const upload=(field,file)=>readImage(file,value=>onUpdate({...trade,[field]:value}));return <><header><div><p>TRADE REVIEW</p><h1>Before / After Screenshots</h1></div></header><section><h2>Upload screenshots</h2>{sorted.length===0?<p>Import or save a trade first, then return here to attach screenshots.</p>:<><label>Select trade<select value={selected} onChange={e=>setSelected(e.target.value)}>{sorted.map(t=><option value={t.id}>{t.date} {t.time} · {t.instrument} · {t.direction} · {money(t.pnl)}</option>)}</select></label>{trade&&<div className="form two screenshotUpload"><label>Before-entry screenshot<input type="file" accept="image/*" onChange={e=>upload('beforeScreenshot',e.target.files?.[0])}/></label><label>After-exit screenshot<input type="file" accept="image/*" onChange={e=>upload('afterScreenshot',e.target.files?.[0])}/></label></div>}<p className="muted">Choose the trade first, then upload one or both screenshots. The image saves immediately to that trade.</p></>}</section>{trade&&<section><h2>{trade.date} · {trade.setup} · {money(trade.pnl)}</h2><div className="compare"><div><h3>Before entry</h3>{trade.beforeScreenshot?<img src={trade.beforeScreenshot}/>:<p>Not added yet</p>}</div><div><h3>After exit</h3>{trade.afterScreenshot?<img src={trade.afterScreenshot}/>:<p>Not added yet</p>}</div></div><div className="promptgrid"><span>Was the bias correct?</span><span>Was the entry early?</span><span>Was the stop structural?</span><span>Did price later reach the target?</span></div></section>}</>}

export function Excursion({trades}){const valid=trades.filter(t=>Number.isFinite(Number(t.mfe))||Number.isFinite(Number(t.mae))),avg=k=>valid.length?valid.reduce((a,t)=>a+Number(t[k]||0),0)/valid.length:0;return <><header><h1>MFE / MAE Analysis</h1></header><div className="cards"><div className="card"><span>Average MFE</span><b>{avg('mfe').toFixed(1)} ticks</b></div><div className="card"><span>Average MAE</span><b>{avg('mae').toFixed(1)} ticks</b></div><div className="card"><span>Trades Tracked</span><b>{valid.length}</b></div></div><section><h2>Stop and target lessons</h2>{valid.length?<table><thead><tr><th>Date</th><th>Setup</th><th>MFE</th><th>MAE</th><th>Net</th><th>Lesson</th></tr></thead><tbody>{valid.map(t=><tr><td>{t.date}</td><td>{t.setup}</td><td>{t.mfe||0}t</td><td>{t.mae||0}t</td><td>{money(t.pnl)}</td><td>{Number(t.mae)>Number(t.stopTicks||0)?'Stop may have been inside normal movement':Number(t.mfe)>Number(t.targetTicks||0)&&t.pnl<=0?'Trade reached target distance before exit':'Collect more samples'}</td></tr>)}</tbody></table>:<p>Add MFE and MAE when editing trades to determine whether stops are too tight or targets are unrealistic.</p>}</section></>}

export function BracketLab({trades,onSave}){const[f,setF]=useState({name:'16T / 32T',stopTicks:16,targetTicks:32,notes:''}),rows=useMemo(()=>{const m={};trades.forEach(t=>{const k=t.bracket||'Unassigned';(m[k]??=[]).push(t)});return Object.entries(m).map(([name,a])=>({name,...stats(a)}))},[trades]);return <><header><h1>Bracket Performance Lab</h1></header><section><h2>Create bracket template</h2><div className="form"><label>Name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Stop ticks<input type="number" value={f.stopTicks} onChange={e=>setF({...f,stopTicks:+e.target.value})}/></label><label>Target ticks<input type="number" value={f.targetTicks} onChange={e=>setF({...f,targetTicks:+e.target.value})}/></label><label>R:R<input disabled value={(f.targetTicks/Math.max(1,f.stopTicks)).toFixed(2)+'R'}/></label><label className="wide">Notes<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></div><button className="primary" onClick={()=>onSave({...f,id:uid()})}>Save Template</button></section><section><h2>Results by bracket</h2>{rows.map(r=><div className="readyrow"><span>{r.name} · {r.count} trades · {r.win.toFixed(0)}% wins</span><b className={r.net>=0?'good':'bad'}>{money(r.net)} · PF {r.pf.toFixed(2)}</b></div>)}</section></>}

export function Coach({trades,settings}){const d=today(),todayTrades=trades.filter(t=>t.date===d),recent=[...trades].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).slice(0,10),bad=recent.filter(t=>t.mistake&&t.mistake!=='None'),low=recent.filter(t=>t.score<settings.minRuleScore),best=[...recent].sort((a,b)=>b.score-a.score)[0],focus=bad.length?`Eliminate ${bad[0].mistake}.`:'Wait for complete confirmation before entry.',lesson=low.length?`${low.length} of your last ${recent.length} trades were below your minimum rule score.`:'Recent rule discipline is acceptable.';return <><header><div><p>BEGINNER COACH</p><h1>Today’s Trading Plan</h1></div></header><section className="coach"><h2>Today’s focus</h2><ul><li>Trade one MES contract.</li><li>Take only A-grade trend pullbacks or clean zone rejections.</li><li>Trade only between the approved session times.</li><li>Stop after {settings.maxTrades} trades or {money(settings.maxDailyLoss)} loss.</li><li>{focus}</li></ul></section><section><h2>Current lesson</h2><p>{lesson}</p>{best&&<p>Your highest-discipline recent trade scored {best.score}/100 using {best.setup}.</p>}</section><section><h2>Today’s status</h2><div className="cards"><div className="card"><span>Trades today</span><b>{todayTrades.length}/{settings.maxTrades}</b></div><div className="card"><span>Today P&L</span><b>{money(todayTrades.reduce((a,b)=>a+b.pnl,0))}</b></div></div></section></>}
